export type PermissionsType = {
  CREATE_INSTANT_INVITE: number,
  KICK_MEMBERS: number,
  BAN_MEMBERS: number,
  ADMINISTRATOR: number,
  MANAGE_CHANNELS: number
  MANAGE_GUILD: number,
  ADD_REACTIONS: number,
  VIEW_AUDIT_LOG: number,
  PRIORITY_SPEAKER: number,
  STREAM: number,
  VIEW_CHANNEL: number,
  SEND_MESSAGES: number,
  SEND_TTS_MESSAGES: number,
  MANAGE_MESSAGES: number,
  EMBED_LINKS: number,
  ATTACH_FILES: number,
  READ_MESSAGE_HISTORY: number,
  MENTION_EVERYONE: number,
  USE_EXTERNAL_EMOJIS: number,
  CONNECT: number,
  SPEAK: number,
  MUTE_MEMBERS: number,
  DEAFEN_MEMBERS: number,
  MOVE_MEMBERS: number,
  USE_VAD: number,
  CHANGE_NICKNAME: number,
  MANAGE_NICKNAMES: number,
  MANAGE_ROLES: number,
  MANAGE_WEBHOOKS: number,
  MANAGE_EMOJIS: number,
} | {
  [key: string]: number;
};
