name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  rust-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build typescript
        run: npm run build
